application:
  subdomain: lazydb-hub
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: file:///lzcapp/pkg/content/
  ingress:
{{if .U.enable_mysql}}
    - protocol: tcp
      port: 3306
      service: percona-server
{{end}}
{{if .U.enable_postgresql}}
    - protocol: tcp
      port: 5432
      service: postgresql
{{end}}
{{if .U.enable_mongodb}}
    - protocol: tcp
      port: 27017
      service: mongodb
{{end}}
{{if .U.enable_redis}}
    - protocol: tcp
      port: 6379
      service: redis
{{end}}

services:
{{if .U.enable_mysql}}
  percona-server:
    # upstream: percona/percona-server:8.4@sha256:20fffeb20bc4801fb527b79c788c4fbadd3241cc3f5a14463dcb706f02090f3e
    image: docker.1ms.run/percona/percona-server:8.4@sha256:20fffeb20bc4801fb527b79c788c4fbadd3241cc3f5a14463dcb706f02090f3e
    environment:
      - MYSQL_ROOT_PASSWORD={{.U.mysql_root_password}}
      - MYSQL_DATABASE={{.U.mysql_database}}
      - MYSQL_USER={{.U.mysql_user}}
      - MYSQL_PASSWORD={{.U.mysql_password}}
    binds:
      - /lzcapp/var/mysql/data:/var/lib/mysql
      - /lzcapp/var/mysql/logs:/var/log/mysql
      - /lzcapp/var/mysql/backups:/backups
{{end}}
{{if .U.enable_postgresql}}
  postgresql:
    # upstream: postgres:16.15
    image: docker.1ms.run/library/postgres:16.15
    environment:
      - POSTGRES_PASSWORD={{.U.postgresql_password}}
      - POSTGRES_DB={{.U.postgresql_database}}
      - POSTGRES_USER={{.U.postgresql_user}}
    binds:
      - /lzcapp/var/postgresql/data:/var/lib/postgresql/data
      - /lzcapp/var/postgresql/backups:/backups
{{end}}
{{if .U.enable_mongodb}}
  mongodb:
    # upstream: mongo:7.0.43
    image: docker.1ms.run/library/mongo:7.0.43
    environment:
      - MONGO_INITDB_ROOT_PASSWORD={{.U.mongodb_root_password}}
      - MONGO_INITDB_DATABASE={{.U.mongodb_database}}
      - MONGO_INITDB_ROOT_USERNAME={{.U.mongodb_user}}
    binds:
      - /lzcapp/var/mongodb/data:/data/db
      - /lzcapp/var/mongodb/backups:/backups
{{end}}
{{if .U.enable_redis}}
  redis:
    # upstream: redis:7.4.11-alpine
    image: docker.1ms.run/library/redis:7.4.11-alpine
    command: ["redis-server", "--requirepass", "{{.U.redis_password}}"]
    binds:
      - /lzcapp/var/redis/data:/data
      - /lzcapp/var/redis/backups:/backups
{{end}}
