package: lazycat.community.app.lazydb-hub
name: LazyDB Hub
version: 0.1.0
min_os_version: 1.3.8
description: Lazycat Database Hub
homepage: https://github.com/lazycat-contrib/lazydb-hub-lzcapp
author: czyt
application:
    subdomain: lazydb-hub
    background_task: true
    public_path:
        - /
    upstreams:
        - location: /
          backend: file:///lzcapp/pkg/content/

    ingress:
{{if .U.enable_mysql}}
         - protocol: tcp
           port: 3306
           service: percona-server
{{end}}

services:
{{if .U.enable_mysql}}
    percona-server:
        image: {{.U.docker_pull_mirror}}/percona/percona-server:8.4
        environment:
            - MYSQL_ROOT_PASSWORD={{.U.mysql_root_password}}
            - MYSQL_DATABASE={{.U.mysql_database}}
            - MYSQL_USER={{.U.mysql_user}}
            - MYSQL_PASSWORD={{.U.mysql_password}}
        binds:
            - /lzcapp/var/mysql/data:/var/lib/mysql
            - /lzcapp/var/mysql/logs:/var/log/mysql
            - /lzcapp/var/mysql/backups:/backups
{{end}}
